### ISSUE TITLE
GitLab CEの最新AMIで初回アクセス画面が表示されない

### ISSUE THREAD

**Issue by nariryo** [cnc4e/ecs-cicd-gitlab#1]
# 背景
GitLab CEの最新AMI：`GitLab CE 13.6.0-4fd521c2-9d5d-4e1a-a34b-66ef9ca0c8e4-ami-0eb2f2c6904f60249.4` で起動されたGitLabにアクセスする場合、初回アクセス画面が表示されない。既にrootユーザが存在し、パスワードを求められてしまう。    
インスタンスの再起動やterraformによる再作成では解決せず。
1つ前のAMI：`GitLab CE 13.5.1-4fd521c2-9d5d-4e1a-a34b-66ef9ca0c8e4-ami-0d0d6a389368caacd.4` では初回アクセス画面が表示され解決する。なお13.6.0のAMIが追加されたのは前回レビュー時から今回レビューまでの間。

[該当箇所](https://github.com/cnc4e/ecs-cicd-gitlab/blob/master/documents/howtouse.md#gitlab%E3%82%B5%E3%83%BC%E3%83%90)

**Comment by nariryo** [comment]
本日`GitLab CE 13.6.1-4fd521c2-9d5d-4e1a-a34b-66ef9ca0c8e4-ami-05a4378c9a1adc7f5.4`がリリースされていたが状況変わらず。

**Comment by moriryota62** [comment]
最新のAMIだとrootのパスワードがあらかじめ設定されており、パスワード不明でログインできない。
これは現時点の最新AMIによる不具合と考えられるため、最新使ってrootのパスワードが設定されていた場合のワークアラウンドとしてAMI IDを取得するコードを修正する方法を案内する。

**Comment by moriryota62** [comment]
sshしてパスワードを変更する方法を思いついたのでAMIの指定を変える方法とパスワードを変える方法の2つをワークアラウンドに追加しました。

b88c4d5d6fbd49d2434510fcfcd7b3459b2b5e84

（勢い余ってmasterにpushしてしまいました。。。）
